ember-cli-deploy/ember-cli-deploy

README.md
Added an example of how to use an reds-db with secret to readme. Took me a while to figure this out.
=> use redis with secret

node-tests/unit/utilities/tagging/sha-test.js, package.json, utilities/tagging/sha.js
Compilable / usable on Windows: removed gitty dependency, added in execSync for getting a git HEAD hash, including tests.
=> Compilable / usable on Windows: removed gitty dependency

.travis.yml, node-tests/unit/utilities/tagging/sha-test.js, utilities/tagging/sha.js
=> add support for execSync in node >= 0.11

README.md, lib/commands/activate.js, lib/commands/assets.js, lib/commands/deploy-index.js, lib/commands/deploy.js, lib/commands/list.js, lib/tasks/activate.js, lib/tasks/assets.js, lib/tasks/deploy-index.js, lib/tasks/list.js, node-tests/fixtures/deploy.js, node-tests/unit/utilities/configuration-reader-test.js
Based on work from jbescoyez in #25, which this PR replaces.
=> Allow custom config file via --deploy-config-file.

package.json
=> Add npm command for running mocha tests autotest-style

lib/commands/deploy.js, lib/models/config.js, lib/tasks/activate.js, lib/tasks/assets.js, lib/tasks/deploy-index.js, lib/tasks/list.js, node-tests/unit/models/config-test.js, node-tests/unit/utilities/configuration-reader-test.js, utilities/configuration-reader.js
=> Encapsulate default configuration in a config model

README.md, package.json
=> Update package.json and README to reflect move to ember-cli org

README.md
Closes #43.
The README needs an overhaul but adding this now will make sure we don't forget about it later.
=> Add note for fingerprint.prepend and staging envs.

README.md
=> Remove quote, typo

README.md
I promise this is the last one @achambers
=> Another incorrect quote

package.json
=> move glob from devDependencies to dependencies

package.json
*Ember London Project Day*
Aaron tested on Mac, and I tested on Windows and this mod works on both. Needs testing on other platforms.
Fixes issue https://github.com/ember-cli/ember-cli-deploy/issues/114
=> Changed package to be able to run tests on windows. 

README.md
No more, no less. About time I did this.
=> Link to ember-deploy-couchbase.

.gitignore, README.md, lib/models/config.js, lib/tasks/assets.js, node-tests/unit/models/config-test.js, node-tests/unit/tasks/assets-test.js
=> Add configuration option to exclude asset files from being deployed.

lib/tasks/activate.js, lib/tasks/assets.js, lib/tasks/deploy-index.js, lib/tasks/list.js, lib/tasks/pipeline.js, lib/utilities/configuration-reader.js, node-tests/fixtures/config/deploy-for-addons-config-test.js, node-tests/unit/tasks/assets-test.js, node-tests/unit/tasks/pipeline-test.js, node-tests/unit/utilities/configuration-reader-test.js
The first commit in this PR was before I realized that ConfigurationReader was not used by the pipeline, so it's good to have it merge, but not relevant to pipeline task operation.
=> Promise-aware config reading and support for `plugins` configuration

README.md
Add my adapter to the list? :)
=> added ember-cli-rest-index adapter to list of adapter

README.md
This will be useful until 0.5, and is more up-to-date than the current talk.
=> Update video link in README.

lib/tasks/pipeline.js, lib/utilities/pipeline.js, node-tests/unit/tasks/pipeline-test.js, node-tests/unit/utilities/pipeline-test.js
=>     Include deployEnvironment as part of context in 0.5.0

README.md, lib/tasks/deploy-index.js, lib/tasks/list.js
Fixes https://github.com/ember-cli/ember-cli-deploy/issues/151
I'd appreciate if someone could give me some advise on how to implement tests ( if there are needed any :) )
=> [#151] read manifestPrefix from config

docs/v0.4.x/installation.md
tossed in (simple) instructions on picking adapters appropriate to their environment. Not sure whether installation is the right chapter for that. Since it's 0.4.x, I didn't bother too much (let's get installation instructions / user flow through discovering all plugins & commands super clear for 0.5)
not sure about the link formatting by the way... didn't work with GH pages before
=> instructions on installing index/assets plugins

lib/commands/list.js
Default displayRevisions adapter at https://github.com/duizendnegen/ember-cli-deploy-display-revisions
Sample implementation of listRevisions in https://github.com/duizendnegen/ember-cli-deploy-azure-tables
=> list pipeline containing fetchRevisions and displayRevisions

rfc/plugins.md
this is a possible first pass, 
feedback in how to restructure/rewrite this is more than welcome :)
=> Update description of hooks in rfc

lib/tasks/pipeline.js
=> Give warning when no plugins are installed

_data/navs.yml, docs/v0.5.x/development-workflow.md
- Pull in post-build task docs from recent PR
=> Introduce a Usage section for 0.5.x website docs

_config.yml, docs/v0.5.x/deployment-context.md
also enable some redcarpet fancier options
=> add documentation for deployment-context object

docs/v0.5.x/pipeline-hooks.md
=> Hooks support docu

docs/v0.5.x/pipeline-overview.md
translated in proper english by @lukemelia
=> add pipeline overview

resources/index.md
- added ember-cli-deploy Github org
- added Aaron's Ember London talk video
- added Mattia Gheda to the ember-cli-deploy core team list
- gave Aaron top billing
=> Updated the Resources page

docs/v0.5.x/plugins-overview.md
as usual, translated by @lukemelia :)
=> documentation for plugins overiew

docs/v0.5.x/pipeline-hooks.md
@lukemelia should be in line with what we discussed.
I've also removed some Notes because they were basically not accurate
let me know what you think!
=> specialized docs for hooks in different commands

resources/index.md
Come back and help when you can @ryanto!
=> Drop Ryan from core team per his request.

blueprints/deploy-config/index.js
=> add postInstall message

docs/v0.5.x/usage-overview.md
I'm not entirely sure what you guys envisioned to be in this page
I took a stab at describing the commands for now
happy to get feedback as usual
/cc @achambers @lukemelia
=> usage overview docu

docs/v0.5.x/development-workflow.md
after finishing updates to demo app @lukemelia spotted a couple of mistakes in the demo config
this puts them on par with the docs
=> tweaks to dev config

docs/v0.5.x/plugins.md
=> slack plugin is now core

docs/v0.5.x/deployment-strategies-overview.md
/cc @achambers @lukemelia 
just a first pass
also have this on a gdoc that I can share w/you guys for easier collaboration
=> first pass ad deploy strategy overview docu

_data/navs.yml, docs/v0.5.x/fingerprinting.md
adds some minor tweaks as well
/cc @lukemelia (sorry for all the pings)
=> port fingerprint docs from 0.4.x

README.md
Configuration and usage links are changed with v0.5.x
=> Correct section links for v0.5.x docs

_data/navs.yml, docs/v0.5.x/upgrading-plugins.md
mainly taken from the UPGRADING.md file on master
=> upgrading plugins docu

_data/navs.yml, docs/v0.5.x/upgrading-apps.md
first basic pass based on what I had to do on the demo app
can definitely be improved
a separate page should be added for plugin authors
=> upgrade apps docs

docs/v0.5.x/configuration-overview.md
This fixes a small typo in some example code in the documentation.
=> fix exports assignment

lib/tasks/pipeline.js, node-tests/unit/tasks/pipeline-test.js
Fixes #226 
Pairing with @jheth I enjoyed the time.
=> Require a deploy target to run ember deploy

docs/v0.5.x/plugins.md
- Also re-alphabetizes community plugins
=> Add ember-cli-deploy-cloudfront plugin

docs/v0.5.x/plugin-packs.md
- Also alphabetize community plugin packs
=> Add ember-cli-deploy-aws-pack

index.js, lib/commands/activate.js, lib/commands/deploy.js, lib/commands/list.js, lib/tasks/deploy.js, lib/tasks/pipeline.js, lib/tasks/read-config.js, node-tests/fixtures/config/deploy-for-addons-config-test.js, node-tests/fixtures/config/deploy.js, node-tests/unit/tasks/deploy-test.js, node-tests/unit/tasks/pipeline-test.js, node-tests/unit/tasks/read-config-test.js
=> read-config task (fix issue where dotenv files were not loaded in time for deploy tasks)

docs/v0.5.x/plugins.md
=> Add CouchDB plug-in

docs/v0.5.x/plugins.md
Add link to ember-cli-deploy-mysql
=> [DOC] Update plugins.md to include link to ember-cli-deploy-mysql

docs/v0.6.x/dotenv-support.md
To document the behavior introduced in #342.
=> Update dotenv documentation.

lib/commands/deploy.js, lib/models/pipeline.js, node-tests/helpers/fake-progress-bar.js, node-tests/unit/models/pipeline-test.js, package.json
first pass at addressing #276 
Remaining TODOs:
http://gsnaps.s3.amazonaws.com/screencast_2016-01-08_14-54-36_0_edited.mp4
=> display progress notification during deploy

_data/navs.yml, docs/v0.6.x/s3-walkthrough.md
Step-by-step guide to putting together a deployment pipeline, as seen at #344, but squashed into a single commit and rebased on the 0.6.x branch.
=> S3 walkthrough

docs/v0.5.x/plugins.md, docs/v0.6.x/plugins.md
=> Add ember-cli-deploy-rollbar to community plugins

docs/v0.5.x/configuration-overview.md, docs/v0.6.x/configuration-overview.md
This implements #355. Any feedback is quite welcomed.
=> Added section on buildEnv and process.env.DEPLOY_TARGET

docs/v0.6.x/configuration-overview.md
Update documentation to match actual implementation and blueprints installed initially by ember-cli-deploy.
=> Fix build environment on Configuration Overview

package.json
- Fixes an issue resulting in crash showing progress bar at certain terminal window sizes
=> Move to non-scoped npm package for progress, and newer version.

lib/commands/activate.js, lib/commands/deploy.js, lib/commands/list.js, lib/models/pipeline.js, node-tests/unit/models/pipeline-test.js
as discussed in https://github.com/ember-cli/ember-cli-deploy/issues/358
coordinated with https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/pull/8
=> add config options for log colors

_config.yml
Explain what changed and why.
Link to related issues in this or other repositories (if any)
Mention people who would be interested in the changeset (if any)
=> Fix asset path

_config.yml
Explain what changed and why.
Link to related issues in this or other repositories (if any)
Mention people who would be interested in the changeset (if any)
=> Fix incorrect baseUrl

docs/v1.0.0-beta.1/configuration.md
Improve advanced config docs based on feedback from @chrislopresto
=> Improve advanced config docs

resources/index.md
I made a big ol' series which will probably be helpful to users of ember-cli-deploy, so I linked to it in the Video Resources section.
=> Add EmberScreencasts series to resources

package.json
Bumped versions for broccoli and brocolli-gzip
https://github.com/ember-cli-deploy/ember-cli-deploy/issues/437
@duizendnegen
=> Bump broccoli and broccoli-gzip versions

docs/docs/v0.5.x/quick-start.md, docs/docs/v0.6.x/quick-start.md, docs/docs/v1.0.0-beta/quickstart.md
=> Update docs for required deploy target

docs/docs/v1.0.x/configuration.md, lib/models/deprecated-plugin-registry.js, node-tests/unit/models/deprecated-plugin-registry-test.js
See https://github.com/ember-cli-deploy/ember-cli-deploy/issues/426
=> fix documentation link in deprecation warning

lib/tasks/read-config.js, node-tests/fixtures/config/empty.js, node-tests/unit/tasks/read-config-test.js, package.json
this happens after not returning anything from the function in `config/deploy.js`
=> Reject undefined config

docs/_data/navs.yml, docs/docs/v1.0.x/in-repo-addon-plugin.md, docs/docs/v1.0.x/in-repo-plugins.md
I'm not sure how much or little detail should go in to this documentation. I'm happy to make revisions if anyone has guidance on what should change or how it should be different :)
Resolves #476
NOTE: I was not able to start the jekyll server without updating the Gemfile.lock (#485).
UPDATE: I merged #485 and rebase this back on master.
=> [DOC] Document creating an ember-cli-deploy plugin as an in-repo-addon

docs/plugins/index.md
Added ember-cli-deploy-cloudformation to docs/plugins
none
=> [DOC] Add ember-cli-deploy-cloudformation

docs/plugins/index.md
I've created behind Trustvox org a [plugin to deploy assets to minio](https://github.com/trustvox/ember-cli-deploy-minio) so If you agree, I want to join the community plugins list!
Thanks for the awesome addon 🚀 
Just me!
=> [DOC] Add ember-cli-deploy-minio to community plugins

docs/plugins/index.md
Add ember-cli-deploy-git plugin in the plugin list.
=> [DOC] Add ember-cli-deploy-git plugin
