- README.md
- deploy.json
- lib/commands/deploy.js
- utilities/configuration-reader.js
A fix for #21
There might be other considerations to make before merging this, but it works for my use case.
This will default to a development build. This may not be ideal, but it seemed better than making any other assumptions. And defaulting to `production` seems like a bad idea.
Another idea, is that we provide a convention in `deploy.json` to pass build properties to the build task. That would potentially decouple the deploy environment from the ember build environment. e.g. `deploy.json` could look like:
```
{
staging: {
build: {
assetHost: 'cdn.bustle.com',
apiHost: 'staging.api.bustle.com'
}
}
}
```
Does that make sense?
> Pass environment down to build task

- README.md
Serve the `index.html` file out of S3 directly or use S3 as storage behind a proxy instead of Redis. Addon written by @Kerry350, feedback welcome!
(Also minor edit: use the scheme for S3 link, and name S3 with a capital S.)
> Link to new S3 Index Adapter

- lib/tasks/assets.js
Quick fix to remove some conflict markers causing issues when calling `uploadAssets()`.
> Removed erroneous conflict markers.

- lib/commands/activate.js
- lib/commands/assets.js
- lib/commands/deploy-index.js
- lib/commands/deploy.js
- lib/commands/list.js
Quality of life change to support `--prod`, `--dev`, `-e production`, etc on all commands similarly to ember-cli's build commands.
Reference [ember-cli build.js](https://github.com/ember-cli/ember-cli/blob/master/lib/commands/build.js)
> Match ember-cli's build command aliases by supporting --prod and --dev

- blueprints/.jshintrc
- blueprints/deploy-config/files/config/deploy.js
- blueprints/deploy-config/index.js
- index.js
- package.json
* Adds `deploy-config` blueprint to `ember generate`
* Populates config/deploy.js with example config
Closes #52
> Add blueprint to auto generate config/deploy.js

- bower.json
- index.js
- node-tests/unit/utilities/adapter-registry-test.js
- node-tests/unit/utilities/tagging/sha-test.js
- package.json
- utilities/adapter-registry.js
Alright, I think I covered getting all of these renamed properly. I left the readme and the changelog be as I expect these to get their own overhaul.
> update ember-deploy references to be ember-cli-deploy

- lib/commands/deploy.js
- lib/commands/unsupported/assets.js
- lib/models/config.js
- lib/tasks/assets.js
- lib/utilities/configuration-reader.js
- node-tests/unit/tasks/assets-test.js
- node-tests/unit/utilities/configuration-reader-test.js
Fix regression to the type of object that was being passed to assets adapters as “config”. Closes #62
* Slight refactoring to AssetsTask to make it’s interaction with AssetsUploader more testable
* this change means we are not being as lazy with default values as before. That’s ok.
* ConfigurationReader now needs to be constructed with a project reference
> Fix regression to the type of object that was being passed to assets adapters as “config”.

- lib/commands/deploy.js
- lib/tasks/activate.js
- lib/tasks/deploy-index.js
- lib/tasks/list.js
Noticed this as a regression. Will work to add some tests around the tasks to catch this in the future but this addresses a the regression for now.
> ensure project is passed into all configuration readers

- README.md
Since it's not a json file, it doesn't need the quotes around all the keys.
Also converted to single quotes for easy parsing, since those are used in other js examples.
> Cleanup config example

- lib/commands/deprecated/activate.js
- lib/commands/deprecated/assets.js
- lib/commands/deprecated/deploy-index.js
- lib/commands/deprecated/deprecated-command.js
- lib/commands/deprecated/versions.js
- lib/commands/index.js
This reverts the commit that moved the original ember-cli-deploy commands to unsupported for users coming to this project from the original ember-cli-deploy package. It also lists a few original `ember-deploy` commands as deprecated also.
@achambers thanks for deprecating and then un-supporting in 2 commits. Made this an easy item to knock out this morning.
This closes issue #72
> Revert Unsupported Commands back to Deprecated for 0.4.0 release

- MIGRATION_STEPS.md
- index.js
- lib/utilities/detect-deprecated-config.js
> npm post install message for users of v0.0.6

- lib/utilities/tagging/sha.js
- node-tests/unit/utilities/tagging/sha-test.js
- package.json
branch is intended to resolve issues around `child_process` `execSync` compatibility among the nodejs versions and platforms it's installed on. [sync-exec](https://www.npmjs.com/package/sync-exec) is a good candidate. Another possible sol'n is latest version of [execSync](https://github.com/mgutz/execSync) as noted by @duizendnegen in https://github.com/ember-cli/ember-cli-deploy/issues/92
This PR uses [sync-exec](https://www.npmjs.com/package/sync-exec) and was confirmed to resolve https://github.com/ember-cli/ember-cli-deploy/issues/92 and is a potential fix for https://github.com/ember-cli/ember-cli-deploy/issues/90
> [BUGFIX] execSync compat issue #92

- README.md
I understand stuff is changing real soon with #59 but I was struggling with getting staging setup to behave exactly like production in terms of fingerprinting, minifying etc right now.
There are a number of other options that are required in ember-cli if a build exactly the same as `--environment production` is desired, which i've now added to the readme.
> Update config around production-like environments

- lib/utilities/configuration-reader.js
- node-tests/unit/utilities/configuration-reader-test.js
This PR will add better messaging when a user tries to run an `ember-cli-deploy` command for an environment for which there exists no configuration.  This most commonly manifests itself when a user does not supply an `--environment` option, running in the default `development` env for which they have not provided config.
This PR explains what the problem is and points the user to the README for more info.
Closes #101
> Provide better error support for missing environment config

- lib/utilities/assets/unknown.js
- node-tests/unit/utilities/assets/unknown-test.js
While developing an index adapter (more on that later), I was getting an unhelpful message;
```
undefined is not a function
TypeError: undefined is not a function
```
This is was because the AdapterRegistry was defaulting to the UnknownAdapter. However unknown adapter was missing the `list` method, so I had to do some manual debugging before I could find it.
> Stub active, list, createTag UnknownAdapter methods

- lib/models/config.js
- lib/tasks/deploy-index.js
In our application, we rely on more than just `index.html` for the front end to function. For example, we integrate with Picmonkey, which returns the user to a URL on our site when they have completed the workflow. _(Rather than using `index.html` and loading Ember and other dependencies and have these URLs be additional routes, because we want it to be very fast to load. So these pages contain a very small amount of Javascript, which communicate with the parent frame or window and then close.)_
To support this, we need Index Adapters to allow for more than one file. The existing method works as it did before, by passing the contents of `index.html`. But by setting the `indexFiles` attribute in the deployment config, the index-adapter's `uploadFiles` method is called instead of `upload`. …
> Index Adapter support for multiple files

- README.md
I know it's just an example and that real code should have more
checking, but people often copy examples verbatim and I wouldn't
want to read a blog post in the future about this cool trick that
lets you read arbitrary redis keys for most apps deployed via
ember-cli-deploy.
The current example allows users to view any key in redis by
passing an appropriate index_key parameter. This is obviously not
desirable. The amendment I propose isn't 100% secure--it's still
possible to read information that happens to have the same prefix
as the manifest. Ideally one would additionally check to see if
the provided index_key existed in the revisions list before
serving it.
While I could update the example to do this check as well, I worry
that doing so would make the example significantly more …
> [DOCUMENTATION] Make Sinatra example a bit more secure

- lib/utilities/pipeline.js
- node-tests/unit/utilities/pipeline-test.js
Some plugins need the ability to react to failures in the deployment
pipeline to for example notify some webservice of the failed deployment.
It is now possible to add a `didFail`-hook to a plugin that gets
executed as soon as a deployment-hook's execution promise rejects.
* add didFail-hook to pipeline
* 'deanonymize' functions in pipeline utility class
> Add didFail-hook

- lib/tasks/pipeline.js
- lib/utilities/pipeline.js
- node-tests/unit/utilities/pipeline-test.js
Previous to this PR we would loop through all keys on the deploy plugin object and register the functions.  This could be error prone.  Instead we now cycle through the list of hooks that the pipeline has been initialised with and then retrieve them from the deploy plugin
> Only register initialised hooks

- lib/commands/deploy.js
- lib/models/config.js
- lib/tasks/assets.js
- lib/tasks/deploy-index.js
- node-tests/unit/models/config-test.js
By default this prevents problems occuring when running both `ember deploy` and `ember serve` (#134).
Includes unit tests showing configurability.
> Add ability to configure build paths, defaulting to tmp/deploy-dist/.

- lib/tasks/pipeline.js
- node-tests/unit/tasks/pipeline-test.js
A plugin pack is an addon with the keyword “ember-cli-deploy-plugin-pack”
and one or more dependent addons that are ember-cli-deploy-plugins.
Note that the plugin pack’s dependent addons should be listed as
dependencies in the pack’s package.json, not as devDependencies.
I expect that plugin packs may also implement a config/deploy.js
blueprint that is auto-executed upon `ember install` of the pack.
> Adds support for “plugin packs” to 0.5.0

- config/deploy.js
- lib/models/config.js
- node-tests/fixtures/config-with-defaults/deploy.js
- node-tests/fixtures/config/deploy.js
- node-tests/unit/utilities/configuration-reader-test.js
This bug was causing custom config options that had defaults to not be used within assets tasks (such as ember-deploy-s3).
See https://github.com/ember-cli/ember-cli-deploy/blob/6b96fe989a24566f80df6a06596678b02d5a45aa/lib/tasks/assets.js#L55
and https://github.com/ember-cli/ember-cli-deploy/blob/6b96fe989a24566f80df6a06596678b02d5a45aa/lib/models/config.js#L44-55
> Fix _materialize using wrong this context

- lib/tasks/activate.js
- lib/tasks/deploy-index.js
Manifest prefix needs to be used for the activate task as well and in all adapters instance.
> Manifest prefix for activate task.

- lib/commands/deprecated/activate.js
- lib/tasks/activate.js
- lib/utilities/adapter.js
- lib/utilities/assets/unknown.js
- lib/utilities/configuration-reader.js
- package.json
It was removed from Ember CLI proper, so we'll need to include this
ourselves now.
Resolves #163.
It'd be nice to get this into a bug fix release :)
> Use silent-error NPM Package

- lib/utilities/configuration-reader.js
The original error and stack is already printed to the console, there is no need to throw a "real" error (because the stack within ember-cli-deploy itself is not useful).
> Use SilentError to log errors when parsing config.

- config/deploy.js
- config/environment.js
- index.js
- lib/models/config.js
- lib/tasks/pipeline.js
- lib/utilities/pipeline.js
- node-tests/fixtures/config-with-defaults/deploy.js
- node-tests/unit/models/config-test.js
- node-tests/unit/tasks/pipeline-test.js
- node-tests/unit/utilities/pipeline-test.js
- rfc/plugins.md
Restructure to support plugin base class.
* Removes `deployment` node in favor of moving ui, config, etc properties to top level of "context".
* Invokes `beforeHook` on a plugin (if defined) before each hook is called.
Merge of this should be coordinated with similar named branch among all 0.5.0 plugins.
Plugin PR's to merge:
> [0.5.0] Plugin base class restructure

- README.md
- lib/commands/activate.js
- lib/commands/deploy.js
- lib/commands/list.js
- lib/tasks/pipeline.js
- node-tests/unit/tasks/pipeline-test.js
- package.json
* Move to `ember deploy <deploy-target> [--activate]` and `ember deploy:activate <deploy-target> --revision=abc123etc`
* Move from DEPLOY_ENVIRONMENT env var to DEPLOY_TARGET env var
* provide `commandOptions` on context instead of `commandLineArgs`
The motivation for this change was to avoid confusion about the term `environment` and be more succinct.
> [BREAKING] New command line args

- docs/v0.4.x/fingerprinting-options-and-staging-environments.md
The build configuration filename was changed from Brocfile.js to ember-cli-build.js in ember-cli 1.13.0
See https://github.com/ember-cli/ember-cli/blob/275cc36807698968050f80ef8c64e8bd6726ba72/CHANGELOG.md#1130
> Update deprecated build configuration filename

- lib/tasks/pipeline.js
- node-tests/fixtures/config/deploy-for-addons-config-test-with-alias.js
- node-tests/fixtures/config/deploy-for-addons-config-test-with-aliases.js
- node-tests/unit/tasks/pipeline-test.js
Hey,
this is my initial attempt of implementing the alias feature for plugins.
I tested with the redis-plugin, which does not correctly use the passed in name yet.
See https://github.com/zapnito/ember-cli-deploy-redis/pull/18 .
BR,
Domme
> Implement aliases to support multiple instances of plugins

- index.js
Previous to [this commit](https://github.com/ember-cli/ember-cli-deploy/commit/42e3c13f863af3108351411bf93d3d45f2c4b258) a user could specify fingerprinting options in `deploy.js` instead of in their `Brocfile.js`.
Due to the renaming of `DEPLOY_ENVIRONMENT` to `DEPLOY_TARGET` in the above commit, this functionality broke.  This PR fixes that.
So, now users can specify fingerprinting options in `deploy.js` like so:
```javascript
module.exports = function(environment) {
return {
fingerprint: {
enabled: environment === 'production',
prepend: 'https://some-url.com/'
}
};
}
```
> Fix bug where fingerprint options in deploy.js don't work

- _data/navs.yml
This fixes a broken link in the docs nav.
> Fix typo: Lightening -> Lightning

- docs/v0.4.x/commands.md
I tried to do a `deploy:index` and was told that it was deprecated and I reckon this holds for `deploy:assets`, too.
> Remove deploy:index and deploy:assets from DOCs

- index.js
- package.json
It was decided that until we can pluginerize asset-rev, we should
continue to set broccoli-asset-rev options in the Brocfile.js
> Remove modifying fingerprint options on `included` hook

- lib/commands/activate.js
- lib/commands/deploy.js
- lib/commands/list.js
- rfc/plugins.md
after discussion with @lukemelia we're proposing to add two extra hooks that should be implemented in every command (like the configure hook)
`setup`
`teardown`
these are useful for things that have to be setup "around" every command like port-forwarding.
@achambers this seems to be inline with what we discussed as well but let me know your feedback!
> add setup and teardown hooks to all commands

- README.md
- index.js
- lib/commands/deploy.js
- lib/tasks/deploy.js
- node-tests/fixtures/config/deploy-postbuild.js
- node-tests/unit/tasks/deploy-test.js
this adds a config option that will trigger a specific pipeline
every time the project is built.
the use case is to enable pushing assets to a store during development
for example: users of the redis plugin could use this config to get
an updated `index.html` in their redis store:
```
if (deployTarget === 'development-postbuild') {
ENV.plugins = ['redis'];
ENV.build = {
environment: 'development'
};
ENV.redis = {
keyPrefix: 'edd-cli',
revisionKey: '__development__',
allowOverwrite: true,
type: 'redis',  // this can be omitted because it is the default
host: 'localhost',
port: 6379,
distDir: function(context) {
return context.commandOptions.buildDir;
}
};
}
```
adding also this to `ember-cli-build.js`
```
emberCLIDeploy: { …
```
> Add support for postBuildDeployHook

- lib/commands/deploy.js
I encountered the `--activate true` option not working and discovered this (presumed) typo. Not sure if there's a great way to write a test for this or if it matters for a typo.
> Correct typo; commandOptions are a local var

- _data/navs.yml
previously I forgot to add the trailing `/` is seems necessary
to mark link as active
> fix active links in docs nav

- docs/v0.5.x/writing-a-plugin.md
When creating an ember-cli-deploy plugin, the base ember-cli-deploy-plugin module needs to be saved in the `package.json` under `dependencies`, not `devDependencies`. Using `ember install` as previously instructed saves ember-cli-deploy-plugin under `devDependencies` (which we don't want) and switching to `npm install --save` saves ember-cli-deploy-plugin under `dependencies` (which we do want).
This change matches the instructions found in the ember-cli-deploy-plugin README: https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/blob/master/README.md
> Use npm install when installing plugin base

- docs/v0.5.x/writing-a-plugin.md
- The live site currently is printing out the `javascript` meant to trigger the syntax on the code block, so I added the extra newline necessary to render this properly
- I also adjusted one word for clarity (changed "specify" to "specifying")
> Update wording and code block format for plugin execution order

- docs/v0.5.x/lightning-strategy-examples.md
current is just the revision id without the prefix so the example doesn't work.
> add on redis key prefix when retrieving current

- docs/v0.5.x/upgrading-apps.md
I’m excited to finally be getting to update to 0.5!
Is it true that this temporary fix is no longer necessary? I have `broccoli-asset-rev` version 2.2.0 and it _seems_ like it’s working.
> Remove temporary fix for broccoli-asset-rev

- docs/v0.5.x/lightning-strategy-examples.md
I wasn't sure if you wanted to replace the current documentation for a Node example, I only did because it was marked as "outdated". 
Let me know if you want me to leave it in :+1:
> updating Node example app documentation

- lib/commands/activate.js
- lib/commands/deploy.js
- lib/commands/list.js
- lib/commands/option-value.js
This is a crude first attempt at using a setting within a project's `.ember-cli` file to get verbose deploy outputs on every deploy by default. It is used by simply adding `"deployVerbose": true` to your project's `.ember-cli` file.
The implementation is inspired by ember-cli's own `usePods` setting (code: https://github.com/ember-cli/ember-cli/blob/3c615aa55dfe6be1adf14ef67e74028b09560138/lib/commands/destroy.js#L68-L70) so that the `--verbose` flag can still be used with `ember deploy` to reverse the default.
Potential areas for feedback:
> Allow command options to be set in .ember-cli file

- README.md
So the default blueprint is run.
> Update README.md to ember install vs. npm install.

- docs/v0.6.x/lightning-strategy-examples.md
Hey there,
as discussed with @ghedamat in https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/issues/17, i added a link to https://github.com/bitaculous/ember-cli-deploy-rack below the Sinatra application.
PS: Hope it is the correct Branch.
PPS: Many thanks for creating Ember CLI Deploy and the ecosystem around!
> Add `ember-cli-deploy-rack` as an alternative for the described Sinatra application.

- docs/v0.5.x/plugins.md
- docs/v0.6.x/plugins.md
`ember-cli-deploy-notifications` was renamed `-webhooks`. That
should be reflected in the plugin docs as well.
> [DOC] Add ember-cli-deploy-webhooks to plugins

- docs/v0.6.x/s3-walkthrough.md
Currently the link to the documentation page `dotenv-support` is broken.
See http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/s3-walkthrough/#uploading-to-s3
This should hopefully fix the link.
> Fix broken link to dotenv-support in docs/s3-walkthrough

- docs/v0.6.x/s3-walkthrough.md
The property name `s3-index` should have quotes, otherwise the JavaScript may not be valid.
This should fix the issue.
> Fix s3-index configuration example in docs/s3-walkthrough

- docs/v0.6.x/lightning-strategy-examples.md
Adds link to Flask-lightning implementation.  For the Pythonistas out there.
> Add Flask example to lightning-strategy-examples.md

- docs/v0.6.x/default-cli-options.md
Wrap the `verbose` option in double-quotes because without
them it's not valid JSON and we get errors.
```
throw "Error when parsing file in " + path + ". Make sure that you have a valid JSON."
^
Error when parsing file in /Users/danny/src/testapp/.ember-cli. Make sure that you have a valid JSON.
```
> Fix the example .ember-cli config

- CHANGELOG.md
- README.md
- blueprints/ember-cli-deploy/index.js
- lib/tasks/pipeline.js
Updates all instances of `http://ember-cli.github.io` and `http://ember-cli.com` to `http://ember-cli-deploy.github.io`
> Update ember-cli links to ember-cli-deploy

- lib/models/pipeline.js
- package.json
The first commit appeared to pass the tests when it still had a reference to 'lodash-node' in `lib/models/pipeline.js`, which makes me a bit skeptical.
> Bump lodash version to remove warning

- lib/models/pipeline.js
- node-tests/unit/models/pipeline-test.js
Since upgrading to lodash `^4.0.0` in v0.6.2 pipeline context merging
has been broken. When your hook result has an object that exists in
the context already (e.g. `distFiles`) then the results of your hook are
no longer concatenated but instead overwrite the existing values.
For example, if you have `context.distFiles` set to `['file1', file2']`
and your hook returns `{distFiles: ['file3']}` then the resulting distFiles
array is now `['file3', 'file2']`, not `['file1', 'file2', 'file3']` as it
was before.
This is because the `_.merge` function used to merge the contexts was
changed in lodash 4 and is now a simple merger that takes an object and
one or more sources to merge into that object; it no longer takes a custom
merge function. To use a merge function you need to change to use …
> Fix plugin context merging in the pipeline model

- lib/tasks/pipeline.js
Hi guys, I just added a method to validate the configured plugins before continuing with the pipeline, it basically checks if the installed ones contains the configured ones.
I think this could be really useful for the user to get a nicer feedback instead of just failing after that and showing an unrelated error: **Cannot convert object to primitive value**
It took me some time to me to realize that I was trying to use a plugin that i didn't had installed...
Not sure if we should also throw an error and finish the process somehow... I'm not that familiar about how do you handle this kind of errors here :)
Thanks!
> Validate configured plugins before continue with pipeline

- docs/v0.6.x/s3-walkthrough.md
Make sure that users know that the `locationType` must be `hash` in order to deploy to s3.
> [DOC] Add note about hash locationType to s3 walkthrough

- lib/commands/activate.js
- lib/commands/list.js
- lib/models/pipeline.js
- lib/tasks/pipeline.js
- node-tests/unit/tasks/pipeline-test.js
A lot of users seem to hit cases where a command is not working properly because of a missing pluging in their setup.
The most common is running `ember deploy:list TARGET` without having `ember-cli-deploy-display-revisions` installed or an equivalent plugin
This PR adds support for a `requiredHooks` configuration parameter for the PipelineTask that we can use to throw an error when none of the available plugins implements the required hook.
What other hook should we require to be implemented for `list` and the other commands (if any)?
Shall we change the format of the `hooks` property to be something like
```
hooks: [
{ name: 'fetchRevisions', required: true}
{ name: 'willUpload', required: false }
]
``` 
or any other format?
https://github.com/ember-cli-deploy/ember-cli-deploy/issues/386 …
> add support for requiredHooks in pipelines

- lib/tasks/deploy.js
- lib/tasks/pipeline.js
- lib/tasks/read-config.js
In the three core tasks, check for existence of `this._super.init` and call it if present. This fixes a CoreObject deprecation.
Fixes #409
> Fix CoreObject init/super deprecation

- config/environment.js
Removed the `something: 'test'` property in `config/environment.js`. Not sure if it was some debugging code that was mistaken left in, or if it serves some legitimate purpose.
It was introduced in 2fafafcd3129041bead33774991aa03f358fb7ee, but a search of the codebase reveals no other use of the string `something` in the code.
None that I could find.
@achambers (the original author of that commit)
> Remove extraneous `something` config value

- docs/v1.0.0-beta.1/including-a-plugin-twice.md
Just updating the plugin alias example for consistency.
Not sure if you want a consistent example through this entire page. As in carrying either `['s3', 's3-backup']` or `['s3-eu', 's3-us']` throughout all examples on this page.
> Make plugin alias example consistent

- lib/models/task.js
- lib/tasks/deploy.js
- lib/tasks/pipeline.js
- lib/tasks/read-config.js
Moved away from using the shared `Task` model from `ember-cli`.
https://github.com/ember-cli-deploy/ember-cli-deploy/issues/358
> Use own task model

- lib/models/plugin-registry.js
- package.json
Use dag-map directly instead of relying on ember-cli, so we can drop the latter as a dependency.
https://github.com/ember-cli-deploy/ember-cli-deploy/issues/358
> Use dag-map instead of ember-cli internal dag

- blueprints/ember-cli-deploy/index.js
* Use ember-cli-deploy.com instead of ember-cli-deploy.github.io
* Remove version from the link
The downside of this is that getting to the quick section is more than one copy paste away
The good part is that this blueprint will not demand changes after changing versions
> Update outdated link in afterInstall message

- docs/plugins/index.md
Fixes a typo in a plugin name in docs.
N/A
N/A
> fix typo in plugin name

- docs/docs/v1.0.x/configuration.md
Using `environment` as a variable name here makes the example slightly
confusing.  This updates to use `deployTarget` throughout, and makes it
clear which file the snippet in question references.
> Tweak examples in Additional Environments section.

- docs/_layouts/docs.html
In https://github.com/ember-cli-deploy/ember-cli-deploy/pull/446 the actual website/docs info was moved from gh-pages branch to master branch, but this link wasn't noticed at the time.
---
Prior to this change the improve this page link pointed at the older gh-pages branch:
https://github.com/ember-cli-deploy/ember-cli-deploy/edit/gh-pages/docs/v1.0.x/configuration.md
After this change, it points at:
https://github.com/ember-cli-deploy/ember-cli-deploy/edit/master/docs/docs/v1.0.x/configuration.md
> Update target for "improve this page" links in docs.

- package.json
as @lolmaus pointed out in https://github.com/ember-cli-deploy/ember-cli-deploy/pull/458
our tests were not running properly anymore
this PR fixes the issue while still using globs
>  Fix test commands to include all tests REDUX

- docs/plugins/index.md
Add ember-cli-deploy-git-artefacts to the community plugin list.
This plugin generates git artefacts into files like
```bash
○ $:> cat dist/branch.txt
release/v1.2
○ $:> cat dist/tag.txt
v1.2.0
○ $:> cat dist/revision.txt
2a8bc4a42a221e038dfec684a98aa2cd521c4ee9
```
Link to related issues in this or other repositories (if any)
Mention people who would be interested in the changeset (if any)
> Add ember-cli-deploy-git-artefacts to the community plugin list

- docs/docs/v1.0.x/upgrading.md
The guide for upgrading from 0.6 to 1.0 contained incorrect syntax for aliasing plugins. The correct syntax is found here: http://ember-cli-deploy.com/docs/v1.0.x/including-a-plugin-twice/
> Fix upgrade guide to have correct syntax for aliasing plugins

- plugins/index.md
* Remove ember-cli-deploy-mysql (deprecated)
* Add ember-cli-deploy-sql
N/A
Just me, myself, and I!
> [DOC] Replace ember-cli-deploy-mysql with -sql

- lib/models/plugin-registry.js
- node-tests/unit/models/plugin-registry-test.js
Using `deployjs`, addons shouldn't need to start with `ember-cli-deploy` necessarily.
> Allow more flexible plugin naming

- docs/plugins/index.md
`ember-cli-deploy-simply-ssh` added to community plugin list. This plugin supports revisions and gzipped data, as well as revision switching using `deploy:list`/`deploy:activate`.
> [DOC] ember-cli-deploy-simply-ssh added to community plugin list

- blueprints/ember-cli-deploy/index.js
- node-tests/unit/blueprint-test.js
Hi! I'm in the process of updating our internal app blueprint at work to include some deploy-related stuff, and it now installs ember-cli-deploy and a plugin pack in one go. Given that, I thought it might be nice to avoid emitting the notice about needing plugins if any were already present.
It doesn't look like the blueprint has any test coverage today, so I didn't add anything to capture this change. If you feel it's worth testing, I'm happy to go back and set something up.
> Only emit the plugins notice after install if none are present

- docs/resources/index.md
Add link to article about using Lambda@Edge for push state routing on S3/CloudFront
Link to related issues in this or other repositories (if any)
Mention people who would be interested in the changeset (if any)
> add link to lambda edge routing article

- lib/tasks/read-config.js
I am pretty tired and couldn't figure out why `ember deploy` wasn't working for me.
I forgot to add a deploy target. 😅 
I think this will help users who get this error understand it better.
> [DOC] Updated Error Message to be simpler to understand

- docs/plugins/index.md
> [DOC] ember-cli-deploy-git-artefacts moved to the new repo

- docs/docs/v1.0.x/plugin-packs.md
- The name of a plugin now uses a dash, not an equals sign
> [DOC] Plugin pack article typo

- blueprints/ember-cli-deploy/files/config/deploy.js
This is no longer needed in the new linting setup.
> remove /* eslint-env node */

- docs/docs/v1.0.x/using-plugins.md
#505 updated the resources page to point to Discord but forgot this other reference on the plugins page.  Figured I'd fix it while I was in the neighborhood!
> Update community link from Slack to Discord
